package:
    name: eman-packaging
    version: '1'

build:
    number: 0
    skip: True  # [win32]

requirements:
    run:
        - cryoem::constructor 2.3.0
        - conda               4.8
        - conda-build         3.18

about:
  summary: Meta-package for eman packaging
