channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-packaging-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
travis:
  secure:
    BINSTAR_TOKEN: FOd+Rt4Gi0VHQDWkVGGveLAuKYqI5vquK8Do8gXLgOk8y3kFOZCebl4OEmgrpDJ0gIfR6o2GfE6BeQe8wannjj0Cy6pVK/CZd+n9lJAISe/7Ex+RkHmU0zG7ShbxHT5vYqC6D303buY+zLpp4oLI9uI+LcnL+Yx5mzS+EvZNzcxB4EWP7XaTgdocE5yqr+YLUJNpnWxjBEG0YMba4ooLEXju0JAdjIQPO/uMA6E9ItQI+4SydGLDnfoMAmH2w93u86ZsjpuREno/dJTaj7iTgwlOsbGhqmhWpXn8I3d3LXKfVD/3d+/A+LcL9zgW4jX57IFmYulJOuPwGtf+NZ/9Dcm0OVu3d1mApWd7mFbxkQl8GFjKMCSUOnMfNyACME89ftPSgC/ayogyqqInkZRItC6IhWBtMWz6x5a5uoWCZiMoa+7Zsk6MPg8ThHNaDsRFF2d4FYNnyUPomBejL9zpYHK8jxLsw6Sae9uKIcIf3CFV6jlxGqNjTePY7h/7bWmy7RYXRRdoA4zs/bgHtFBTeGuzRMQK5jY+xLftTncUHswjP+BoRLjG2jIiBYHBgvi/NBMwA+Ks4m3M/75TvtrS9pGksDZVRZie6EgH7MiajDC7175EwLGeegcyJMZjIsywLTsGPLiLEmTyph58b3vpB+WiC0b331ACGbcVnH3IN6o=
appveyor:
  secure:
    BINSTAR_TOKEN: DytmJU8Iq1lbelvMvcsTjak25U7QPYCTMr8QmMzqRw21AmRfcLQhfuNPZtjH13q9
