channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-packaging-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
travis:
  secure:
    BINSTAR_TOKEN: ArPoYvxrUNmKH8azPaE3JdyBaN8Bsq1xFKGP6CSFUVxnCCXHMZD7J7ehdSL0wix/hbTyYoomO69CMTGT+N6ZtLbwS50cIJkg8ek1XCw2ghpxl2TlvabZzkaq5ioiYDMfkUrhmmoWnV0UOJ+oPlp5RFHWeVFF0FiNsdW4432YnnQQ3Kj74TavqSm9IoGzv43KbJNaByip05bDSve6WeHTubvHfQhSkOMVww3Rq4F8bBbUKoOhrJ8xIjUMZua9P0M/LbAg7eKciPF80XtL8dpdrgWHoIo7YGTy6WNiKVB8rYqiwdi8fwGAVcbTGCrH4yzYRS8TK23XV82noMu7h+Gx0iWCroRu+OxNsAA8Xt7O76ZnkZ/L5ZcQ+nesUbPOU+R5MRU7aX3v0mZ4WGUHVIneBlaVixFZegy4ybYq8hfN6H52h/NiSfxwqISzWI9d57+D10EYdcgnkpt8B0YklUb3FNDbpLsDeWRyWMmrGrYTeJaGaNAKS2AWjNkWx1wcOFvGoGt8RA2BjEwZKeVAA3g4t9PYjZOE1+Ncu7098WxGYfk/CC8YWrfpEtk5+YUvD633ffZ3hacj14R3DnjkZ19cH69BbvcG6jTM9vVfOaJ4Vgu0OJyU7bqJZF/o6Wh0h7X5jTouInvpbeS7PjGJDPpz+kvdxtWsUkuxm88CqWUQ9eo=
appveyor:
  secure:
    BINSTAR_TOKEN: hhS98dVbKVMiq1d7IEUyMCfA9Be1YSA2+BfDYf+1wwLYdOoWLWVaehGr6/mjqeAv
